name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-slim
    steps:
      - name: Set up Git repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: Homebrew/actions/setup-ruby@18fcb8e3e06b4247c676c506750dc95ea7226479 # 2026.07.13.1
        with:
          setup-homebrew: true
          bundler-cache: true

      - name: Run HTML Proofer tests
        run: bundle exec rake test

  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@18fcb8e3e06b4247c676c506750dc95ea7226479 # 2026.07.13.1

      - name: Install vale
        uses: Homebrew/actions/cache-homebrew-prefix@18fcb8e3e06b4247c676c506750dc95ea7226479 # 2026.07.13.1
        with:
          install: vale

      - name: Run Vale linting on Markdown files
        run: vale --config="$(brew --repo)"/.vale.ini _posts/

  check-redirects:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check release notes redirect
        run: ruby ./.github/actions/check-redirects.rb
