name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-slim
    steps:
      - name: Set up Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: Homebrew/actions/setup-ruby@df4b09108a1de9d6f995fe68f302b3f68bd6d2ef # 2026.07.20.1
        with:
          setup-homebrew: true
          bundler-cache: true

      - name: Run HTML Proofer tests
        run: bundle exec rake test

  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@df4b09108a1de9d6f995fe68f302b3f68bd6d2ef # 2026.07.20.1

      - name: Install vale
        uses: Homebrew/actions/cache-homebrew-prefix@df4b09108a1de9d6f995fe68f302b3f68bd6d2ef # 2026.07.20.1
        with:
          install: vale

      - name: Run Vale linting on Markdown files
        run: vale --config="$(brew --repo)"/.vale.ini _posts/

  check-redirects:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check release notes redirect
        run: ruby ./.github/actions/check-redirects.rb
